### ISSUE TITLE
Can we cache the JniEnv？

### ISSUE THREAD

**Issue by VomPom** [ctrysbita/flutter_native_channel#1]
like follow code:
  SendSynchronousMessageToPlatform(int64_t channel, uint64_t length,  uint8_t *data) {
       static JniEnv env;
}
By adding a static keyword to cache JniEnv, so when next to invoke this method which can save time. 
Don't worry about the different threads when using static keyword, because every time invoke this method in the same thread (Platform thread).

**Comment by ctrysbita** [comment]
Actually this method will be invoked in ui thread.
But the edge case is using synchronous channel in different isolates (by `compute` function).

I think we can cache the env since this method will normally be invoked in same thread.
Have you tried it?

**Comment by VomPom** [comment]
yep, I try it using `compute` or  `Isolate.spawn()` will not be invoked in the main thread, so take ` Isolate.current.debugName` to native, and judge the thread like this:
```
if (thread_name != main_thread) {
    //
} else {
  //
}

```
Though more complex than before but It works on a different thread.
